global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: adsb_fi_exporter
    scrape_interval: 15m
    scrape_timeout: 30s
    metrics_path: /probe
    params:
      module: ["adsb-fi"]
    static_configs:
      - targets:
          - https://api.adsb.fi/v1/stats
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [module]
        target_label: __param_module
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: json_exporter:7979
  - job_name: adsb_fi_aircraft_exporter
    scrape_interval: 5m
    scrape_timeout: 30s
    metrics_path: /probe
    params:
      module: ["adsb-fi-aircraft"]
    static_configs:
      - targets:
          - https://api.adsb.fi/v1/stats
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [module]
        target_label: __param_module
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: json_exporter:7979
  - job_name: airplanes_live_exporter
    scrape_interval: 15m
    scrape_timeout: 30s
    metrics_path: /probe
    params:
      module: ["airplanes-live"]
    static_configs:
      - targets:
          - https://api.airplanes.live/stats
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [module]
        target_label: __param_module
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: json_exporter:7979
  - job_name: airplanes_live_aircraft_exporter
    scrape_interval: 5m
    scrape_timeout: 30s
    metrics_path: /probe
    params:
      module: ["airplanes-live-aircraft"]
    static_configs:
      - targets:
          - https://api.airplanes.live/stats
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [module]
        target_label: __param_module
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: json_exporter:7979
  - job_name: adsb_lol_exporter
    scrape_interval: 15m
    scrape_timeout: 30s
    metrics_path: /probe
    params:
      module: ["adsb-lol"]
    static_configs:
      - targets:
          - https://api.adsb.lol/api/0/me
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [module]
        target_label: __param_module
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: json_exporter:7979
  - job_name: adsb_lol_aircraft_exporter
    scrape_interval: 5m
    scrape_timeout: 30s
    metrics_path: /probe
    params:
      module: ["adsb-lol-aircraft"]
    static_configs:
      - targets:
          - https://api.adsb.lol/api/0/me
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [module]
        target_label: __param_module
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: json_exporter:7979
  - job_name: adsb_one_mlat_exporter
    scrape_interval: 15m
    scrape_timeout: 30s
    metrics_path: /probe
    params:
      module: ["adsb-one-mlat"]
    static_configs:
      - targets:
          - https://api.adsb.one/clients/mlat
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [module]
        target_label: __param_module
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: json_exporter:7979
  - job_name: adsb_one_beast_exporter
    scrape_interval: 15m
    scrape_timeout: 30s
    metrics_path: /probe
    params:
      module: ["adsb-one-beast"]
    static_configs:
      - targets:
          - https://api.adsb.one/clients/beast
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [module]
        target_label: __param_module
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: json_exporter:7979
  - job_name: TAT_exporter
    scrape_interval: 15m
    scrape_timeout: 30s
    metrics_path: /probe
    params:
      module: ["TAT"]
    static_configs:
      - targets:
          - https://theairtraffic.com/api/stats.json/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [module]
        target_label: __param_module
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: json_exporter:7979
  - job_name: airframes_exporter
    scrape_interval: 15m
    scrape_timeout: 30s
    metrics_path: /probe
    params:
      module: ["airframes"]
    static_configs:
      - targets:
          - https://api.airframes.io/v1/stats
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [module]
        target_label: __param_module
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: json_exporter:7979
  - job_name: airframes_aircraft_exporter
    scrape_interval: 5m
    scrape_timeout: 30s
    metrics_path: /probe
    params:
      module: ["airframes-aircraft"]
    static_configs:
      - targets:
          - https://api.airframes.io/v1/stats
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [module]
        target_label: __param_module
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: json_exporter:7979
  - job_name: adsbx_exporter
    scrape_interval: 15m
    scrape_timeout: 30s
    static_configs:
      - targets:
          - http://adsbx_exporter:19100
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: adsbx_exporter:19100

# Uncomment if you want to send data to grafana cloud
# remote_write:
# - url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
#   basic_auth:
#     username:
#     password:
