modules:
  adsb-fi:
    metrics:
      - name: mlat_feeders
        help: ADS-B.fi MLAT Feeder count.
        path: "{ .mlatFeeders }"
        labels:
          aggregator: adsb-fi
      - name: beast_feeders
        help: ADS-B.fi BEAST Feeder count.
        path: "{ .beastFeeders }"
        labels:
          aggregator: adsb-fi
  adsb-fi-aircraft:
    metrics:
      - name: aircraft
        help: ADS-B.fi tracked aircraft count.
        path: "{ .totalAircraft }"
        labels:
          aggregator: adsb-fi
  airplanes-live:
    metrics:
      - name: beast_feeders
        help: airplanes.live beast feeder count
        path: "{ .beast }"
        labels:
          aggregator: airplanes.live
      - name: mlat_feeders
        help: airplanes.live mlat feeder count
        path: "{ .mlat }"
        labels:
          aggregator: airplanes.live
  airplanes-live-aircraft:
    metrics:
      - name: aircraft
        help: airplanes.live tracked aircraft count
        path: "{ .aircraft }"
        labels:
          aggregator: airplanes.live
  adsb-lol:
    metrics:
      - name: mlat_feeders
        help: ADS-B.lol MLAT Feeder count.
        path: "{ .global.mlat }"
        labels:
          aggregator: adsb-lol
      - name: beast_feeders
        help: ADS-B.lol BEAST Feeder count.
        path: "{ .global.beast }"
        labels:
          aggregator: adsb-lol
  adsb-lol-aircraft:
    metrics:
      - name: aircraft
        help: ADS-B.lol tracked aircraft count.
        path: "{ .global.planes }"
        labels:
          aggregator: adsb-lol
  adsb-one-mlat:
    metrics: 
      - name: mlat_feeders
        help: ADS-B.one MLAT Feeder count.
        path: "{ .client_count }"
        labels:
          aggregator: adsb-one
  adsb-one-beast:
    metrics: 
      - name: beast_feeders
        help: ADS-B.one BEAST Feeder count.
        path: "{ .clients }"
        labels:
          aggregator: adsb-one
  TAT:
    metrics: 
      - name: mlat_feeders
        help: TheAirTraffic.com MLAT Feeder count.
        path: "{ .mlat_clients }"
        labels:
          aggregator: TAT
      - name: beast_feeders
        help: TheAirTraffic.com BEAST Feeder count.
        path: "{ .readsb_clients }"
        labels:
          aggregator: TAT
  airframes:
    metrics: 
      - name: other_feeders
        help: Airframes.io MLAT Feeder count.
        path: "{ .stats.stations.active.total }"
        labels:
          aggregator: airframes
  airframes-aircraft:
    metrics: 
      - name: aircraft
        help: Airframes.io tracked aircraft count.
        path: "{ .stats.airframes.flights.active }"
        labels:
          aggregator: airframes
